name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_BUILDKIT: 1

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: make copy-envs

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --build-arg MAKEFLAGS="-j2" \
            -t test-app .

      - name: Test Docker image
        run: |
          echo "=== Testing image build ==="
          docker run --rm --user root test-app python --version
          docker run --rm --user root test-app pip list | head -10

      - name: Run Dependencies Installation
        run: |
          docker run --rm \
            --user root \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            test-app \
            make dependencies

      - name: Run Lint
        run: |
          docker run --rm \
            --user root \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            test-app \
            make lint

      - name: Run Tests
        run: |
          docker run --rm \
            --user root \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            test-app \
            make test-coverage

      - name: Upload coverage (if exists)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/
          if-no-files-found: ignore
